In [18]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [19]:
import sys

sys.path.append(f"./../")

In [20]:
from vqf.preprocessing import create_clauses
from IPython.display import display
from src import Clause, BitsTable

In [21]:
p = 11
q = 7

m = p * q

_, _, _, simple_clauses = create_clauses(m, apply_preprocessing=True, verbose=False)

for c in simple_clauses:
    display(c)

0

0

p_2 + 2*q_1 + q_2 - 2*z_2_3 - 1

p_2*q_1 + p_3 + q_1*q_2 + q_3 + z_2_3 - 2*z_3_4 - 4*z_3_5 - 1

p_2*q_2 + p_3*q_1 + p_4 + q_1*q_3 + z_3_4 - 2*z_4_5 - 4*z_4_6

p_2*q_3 + p_3*q_2 + p_4*q_1 + p_5 + z_3_5 + z_4_5 - 2*z_5_6

p_3*q_3 + p_4*q_2 + p_5*q_1 + p_6 + z_4_6 + z_5_6 - 1

p_4*q_3 + p_5*q_2 + p_6*q_1

p_5*q_3 + p_6*q_2

p_6*q_3

In [22]:
clause = simple_clauses[3]
clause = Clause(clause)
bits = clause.bits

In [23]:
bits

{p_2, p_3, q_1, q_2, q_3, z_2_3, z_3_4, z_3_5}

In [24]:
table = clause.reduce_space()
table.calc_r()

    z_2_3  z_3_5  q_2  q_3  z_3_4  p_3  q_1  p_2
0       0      0    0    0      0    0    1    1
1       0      0    0    0      0    1    0    0
2       0      0    0    0      0    1    0    1
3       0      0    0    0      0    1    1    0
4       0      0    0    1      0    0    0    0
5       0      0    0    1      0    0    0    1
6       0      0    0    1      0    0    1    0
7       0      0    0    1      1    1    1    1
8       0      0    1    0      0    0    1    0
9       0      0    1    0      0    1    0    0
10      0      0    1    0      0    1    0    1
11      0      0    1    0      1    1    1    1
12      0      0    1    1      0    0    0    0
13      0      0    1    1      0    0    0    1
14      0      0    1    1      1    0    1    1
15      0      0    1    1      1    1    1    0
16      1      0    0    0      0    0    0    0
17      1      0    0    0      0    0    0    1
18      1      0    0    0      0    0    1    0
19      1      0    0    0      1    1    1    1
20      1      0    0    1      1    0    1    1
21      1      0    0    1      1    1    0    0
22      1      0    0    1      1    1    0    1
23      1      0    0    1      1    1    1    0
24      1      0    1    0      0    0    0    0
25      1      0    1    0      0    0    0    1
26      1      0    1    0      1    0    1    1
27      1      0    1    0      1    1    1    0
28      1      0    1    1      1    0    1    0
29      1      0    1    1      1    1    0    0
30      1      0    1    1      1    1    0    1
31      1      1    1    1      0    1    1    1

-3.0

In [25]:
new_table = table.remove_carry_bits()
new_table.calc_r()

    q_2  q_3  p_3  q_1  p_2
0     0    0    0    1    1
1     0    0    1    0    0
2     0    0    1    0    1
3     0    0    1    1    0
4     0    1    0    0    0
5     0    1    0    0    1
6     0    1    0    1    0
7     0    1    1    1    1
8     1    0    0    1    0
9     1    0    1    0    0
10    1    0    1    0    1
11    1    0    1    1    1
12    1    1    0    0    0
13    1    1    0    0    1
14    1    1    0    1    1
15    1    1    1    1    0
16    0    0    0    0    0
17    0    0    0    0    1
18    0    0    0    1    0
19    0    0    1    1    1
20    0    1    0    1    1
21    0    1    1    0    0
22    0    1    1    0    1
23    0    1    1    1    0
24    1    0    0    0    0
25    1    0    0    0    1
26    1    0    0    1    1
27    1    0    1    1    0
28    1    1    0    1    0
29    1    1    1    0    0
30    1    1    1    0    1
31    1    1    1    1    1

0.0

In [26]:
new_table.bits

{p_2, p_3, q_1, q_2, q_3}